# Generated by Django 4.1.4 on 2024-01-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinformation',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
